---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-1
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.nfs-storage.svc.cluster.local
  share: /
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  annotations:
    snapshot.storage.k8s.io/is-default-class: "true"
    k10.kasten.io/is-snapshot-class: "true"
kind: VolumeSnapshotClass
metadata:
  name: csi-nfs-snapclass
driver: nfs.csi.k8s.io
deletionPolicy: Delete
