apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  labels:
    formation_id: mas-masdev-masdev-manage
  name: mas-masdev-masdev-manage
  namespace: db2u  
spec:
  account:
    privileged: true
  addOns:
    qrep:
      infraHost: xxx.ibm.com
      infraIP: x.x.x.x
      license: {}
      linktype: public
  environment:
    database:
      dbConfig:
        APPLHEAPSZ: 8192 AUTOMATIC
        AUTHN_CACHE_DURATION: "10"
        AUTHN_CACHE_USERS: "100"
        AUTO_DB_BACKUP: "OFF"
        AUTO_DEL_REC_OBJ: "ON"
        AUTO_MAINT: "ON"
        AUTO_REORG: "OFF"
        AUTO_REVAL: DEFERRED
        AUTO_RUNSTATS: "ON"
        AUTO_TBL_MAINT: "ON"
        CATALOGCACHE_SZ: "800"
        CHNGPGS_THRESH: "40"
        CUR_COMMIT: "ON"
        DATABASE_MEMORY: AUTOMATIC
        DBHEAP: AUTOMATIC
        DDL_CONSTRAINT_DEF: "YES"
        DEC_TO_CHAR_FMT: NEW
        DFT_QUERYOPT: "5"
        DFT_TABLE_ORG: ROW
        LOCKLIST: AUTOMATIC
        LOCKTIMEOUT: "300"
        LOGARCHMETH1: DISK:/mnt/bludata0/db2/archive_log/
        LOGBUFSZ: "1024"
        LOGFILSIZ: "32768"
        LOGPRIMARY: "100"
        LOGSECOND: "156"
        MAXFILOP: "61440"
        MIRRORLOGPATH: /mnt/backup
        NUM_DB_BACKUPS: "60"
        NUM_IOCLEANERS: AUTOMATIC
        NUM_IOSERVERS: AUTOMATIC
        PCKCACHESZ: AUTOMATIC
        REC_HIS_RETENTN: "60"
        SOFTMAX: "0"
        STAT_HEAP_SZ: AUTOMATIC
        STMT_CONC: LITERALS
        STMTHEAP: "20000"
        TRACKMOD: "YES"
        WLM_ADMISSION_CTRL: "NO"
      name: BLUDB
      settings:
        dftTableOrg: ROW
    dbType: db2wh
    instance:
      dbmConfig:
        AGENT_STACK_SZ: "1024"
        FENCED_POOL: "50"
        HEALTH_MON: "OFF"
        KEEPFENCED: "NO"
        MON_HEAP_SZ: AUTOMATIC
        RQRIOBLK: "65535"
      password: '[secure]'
      registry:
        DB2_4K_DEVICE_SUPPORT: "ON"
        DB2_BCKP_PAGE_VERIFICATION: "TRUE"
        DB2_CDE_REDUCED_LOGGING: REDUCED_REDO:NO
        DB2_EVALUNCOMMITTED: "YES"
        DB2_FMP_COMM_HEAPSZ: "65536"
        DB2_FMP_RUN_AS_CONNECTED_USER: "NO"
        DB2_INLIST_TO_NLJN: "YES"
        DB2_MINIMIZE_LISTPREFETCH: "Y"
        DB2_OBJECT_STORAGE_LOCAL_STAGING_PATH: /mnt/backup/staging
        DB2_SKIPDELETED: "ON"
        DB2_SKIPINSERTED: "ON"
        DB2_USE_ALTERNATE_PAGE_CLEANING: "ON"
        DB2_WORKLOAD: MAXIMO
        DB2AUTH: OSAUTHDB,ALLOW_LOCAL_FALLBACK,PLUGIN_AUTO_RELOAD
    ldap:
      blueAdminPassword: '[secure]'
      enabled: true
      password: '[secure]'
    mln:
      total: 1
  license:
    accept: true
  podConfig:
    db2u:
      resource:
        db2u:
          limits:
            cpu: "6"
            memory: 12Gi
          requests:
            cpu: 300m
            memory: 8Gi
  size: 1
  storage:
  - name: meta
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: ocs-storagecluster-cephfs
    type: create
  - name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: ocs-storagecluster-ceph-rbd
    type: template
  - name: backup
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: ocs-storagecluster-cephfs
    type: create
  - name: activelogs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: ocs-storagecluster-ceph-rbd
    type: template
  - name: tempts
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: ocs-storagecluster-cephfs
    type: template
  version: s11.5.9.0-cn2
