apiVersion: config.kio.kasten.io/v1alpha1
kind: BlueprintBinding
metadata:
  name: cassandra-bp-binding  
  namespace: kasten-io
spec:
  blueprintRef:
    name: cassandra-bp
    namespace: kasten-io
  resources:
    matchAll:
    - type:
        operator: In
        values:
        - group: cassandra.datastax.com
          resource: cassandradatacenter
    # allow the blueprint to be applied to resources that do not have the annotation
    - annotations:
        key: kanister.kasten.io/blueprint
        operator: DoesNotExist
