# we overrind the kanister builtin blueprint
# to avoid calling medusa 
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: k10-k8ssandra-bp-0.0.5
  namespace: kasten-io
actions:
  backup:   
    outputArtifacts:
      cassandraCloudDump:
        keyValue:          
          foo: bar
    phases:    
    - func: KubeTask
      name: noOpsBackup      
      args:
        image: michaelcourcy/kasten-tools:7.5.1
        command:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            echo "noOps"  
  restore:
    inputArtifactNames:
      - cassandraCloudDump
    phases:
    - func: KubeTask
      name: noOpsRestore
      args:
        image: michaelcourcy/kasten-tools:7.5.1
        command:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            echo "noOps"   
  delete:
    inputArtifactNames:
    - cassandraCloudDump
    phases:
    - func: KubeTask
      name: noOpsDelete
      args:
        image: michaelcourcy/kasten-tools:7.5.1
        command:
          - bash
          - -o
          - errexit
          - -o
          - pipefail
          - -c
          - |
            echo "noOps"