apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongoce-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mongoce-backup
  labels:
    app: mongoce-backup
spec:
  securityContext: 
    runAsNonRoot: true 
    seccompProfile: 
      type: "RuntimeDefault"
  containers:
  - name: mongoce-backup
    image: mongo:6.0
    command: ["/bin/bash", "-c", "while true; do sleep 30; done"]
    env:
    - name: MONGO_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mas-mongo-ce-admin-admin
          key: password        
    volumeMounts:
    - name: tls-ca
      mountPath: /var/lib/tls/ca
      readOnly: true
    - name: tls-secret
      mountPath: /var/lib/tls/server
      readOnly: true
    - name: backup-storage
      mountPath: /data/mongo/dumps
  volumes:
  - name: tls-ca
    secret:
      secretName: mas-mongo-ce-ca-certificate
      items:
        - key: ca.crt
          path: ca.crt
  - name: tls-secret
    secret:
      secretName: mas-mongo-ce-server-certificate-key
      items:
        - key: mongo.pem
          path: mongo.pem
  - name: backup-storage
    persistentVolumeClaim:
      claimName: mongoce-backup-pvc
  restartPolicy: Never